version: '2.0.1'

services:
  consignment:
    restart: always
    # build: -f ./shippy-service-consignment .
    image: shippy-service-consignment
    depends_on:
      - datastore
      - vessel
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  vessel:
    restart: always
    # build: -f ./shippy-service-vessel .
    image: shippy-service-vessel
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  cli:
    # build: ./shippy-cli-consignment
    image: shippy-cli-consignment


  datastore:
    image: mongo
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017
    command: mongod --logpath=/dev/null
